In [1]:
# !pip install lightfm 

In [2]:
# !pip install implicit

In [3]:
import pandas as pd
import numpy as np

from scipy.sparse import csr_matrix, coo_matrix

from lightfm import LightFM
from lightfm.evaluation import precision_at_k

In [4]:
data = pd.read_csv('retail_train.csv')
item_features = pd.read_csv('product.csv')
user_features = pd.read_csv('hh_demographic.csv')

item_features.columns = [col.lower() for col in item_features.columns]
user_features.columns = [col.lower() for col in user_features.columns]

item_features.rename(columns={'product_id': 'item_id'}, inplace=True)
user_features.rename(columns={'household_key': 'user_id'}, inplace=True)

In [5]:
test_size_weeks = 3

data_train = data[data['week_no'] < data['week_no'].max() - test_size_weeks]
data_test = data[data['week_no'] >= data['week_no'].max() - test_size_weeks]

data_train.head(2)

user_id    basket_id  day  item_id  quantity  sales_value  store_id  \
0     2375  26984851472    1  1004906         1         1.39       364   
1     2375  26984851472    1  1033142         1         0.82       364   

   retail_disc  trans_time  week_no  coupon_disc  coupon_match_disc  
0         -0.6        1631        1          0.0                0.0  
1          0.0        1631        1          0.0                0.0

In [6]:
item_features.head(2)

item_id  manufacturer    department     brand            commodity_desc  \
0    25671             2       GROCERY  National                  FRZN ICE   
1    26081             2  MISC. TRANS.  National  NO COMMODITY DESCRIPTION   

            sub_commodity_desc curr_size_of_product  
0          ICE - CRUSHED/CUBED                22 LB  
1  NO SUBCOMMODITY DESCRIPTION

In [7]:
user_features.head(2)

age_desc marital_status_code income_desc homeowner_desc      hh_comp_desc  \
0      65+                   A      35-49K      Homeowner  2 Adults No Kids   
1    45-54                   A      50-74K      Homeowner  2 Adults No Kids   

  household_size_desc kid_category_desc  user_id  
0                   2      None/Unknown        1  
1                   2      None/Unknown        7

In [8]:
user_features.age_desc.unique()

array(['65+', '45-54', '25-34', '35-44', '19-24', '55-64'], dtype=object)

In [9]:
user_features.income_desc.unique()

array(['35-49K', '50-74K', '25-34K', '75-99K', 'Under 15K', '100-124K',
       '15-24K', '125-149K', '150-174K', '250K+', '175-199K', '200-249K'],
      dtype=object)

In [10]:
user_features.hh_comp_desc.unique()

array(['2 Adults No Kids', '2 Adults Kids', 'Single Female', 'Unknown',
       'Single Male', '1 Adult Kids'], dtype=object)

In [11]:
user_item_matrix = pd.pivot_table(data_train, 
                                  index='user_id', columns='item_id', 
                                  values='quantity',
                                  aggfunc='count', 
                                  fill_value=0
                                 )

user_item_matrix = user_item_matrix.astype(float)
sparse_user_item = csr_matrix(user_item_matrix).tocsr()

user_item_matrix.tail(2)

item_id  25671     26081     26093     26190     26355     26426     26540     \
user_id                                                                         
2499          0.0       0.0       0.0       0.0       0.0       0.0       0.0   
2500          0.0       0.0       0.0       0.0       0.0       0.0       0.0   

item_id  26601     26636     26691     ...  17328742  17329473  17329749  \
user_id                                ...                                 
2499          0.0       0.0       0.0  ...       0.0       0.0       0.0   
2500          0.0       0.0       0.0  ...       0.0       0.0       0.0   

item_id  17330255  17330511  17381856  17382205  17383227  17827644  17829232  
user_id                                                                        
2499          0.0       0.0       0.0       0.0       0.0       0.0       0.0  
2500          0.0       0.0       0.0       0.0       0.0       0.0       0.0  

[2 rows x 86865 columns]

In [12]:
data_test = data_test[data_test['item_id'].isin(data_train['item_id'].unique())]
test_user_item_matrix = pd.pivot_table(data_test, 
                                  index='user_id', columns='item_id', 
                                  values='quantity',
                                  aggfunc='count', 
                                  fill_value=0
                                 )

test_user_item_matrix = user_item_matrix.astype(float)

In [13]:
userids = user_item_matrix.index.values
itemids = user_item_matrix.columns.values

matrix_userids = np.arange(len(userids))
matrix_itemids = np.arange(len(itemids))

id_to_itemid = dict(zip(matrix_itemids, itemids))
id_to_userid = dict(zip(matrix_userids, userids))

itemid_to_id = dict(zip(itemids, matrix_itemids))
userid_to_id = dict(zip(userids, matrix_userids))

**Prepare users and items features**

In [14]:
user_feat = pd.DataFrame(user_item_matrix.index)
user_feat = user_feat.merge(user_features, on='user_id', how='left')
user_feat.set_index('user_id', inplace=True)

item_feat = pd.DataFrame(user_item_matrix.columns)
item_feat = item_feat.merge(item_features, on='item_id', how='left')
item_feat.set_index('item_id', inplace=True)

user_feat.head(2)

age_desc marital_status_code income_desc homeowner_desc  \
user_id                                                           
1            65+                   A      35-49K      Homeowner   
2            NaN                 NaN         NaN            NaN   

             hh_comp_desc household_size_desc kid_category_desc  
user_id                                                          
1        2 Adults No Kids                   2      None/Unknown  
2                     NaN                 NaN               NaN

In [15]:
user_feat_lightfm = pd.get_dummies(user_feat, columns=user_feat.columns.tolist())
item_feat_lightfm = pd.get_dummies(item_feat, columns=item_feat.columns.tolist())

In [16]:
user_feat_lightfm.tail(2)

age_desc_19-24  age_desc_25-34  age_desc_35-44  age_desc_45-54  \
user_id                                                                   
2499                  0               1               0               0   
2500                  0               0               0               0   

         age_desc_55-64  age_desc_65+  marital_status_code_A  \
user_id                                                        
2499                  0             0                      0   
2500                  0             0                      0   

         marital_status_code_B  marital_status_code_U  income_desc_100-124K  \
user_id                                                                       
2499                         0                      1                     0   
2500                         0                      0                     0   

         ...  hh_comp_desc_Unknown  household_size_desc_1  \
user_id  ...                                                
2499     ...                     0                      0   
2500     ...                     0                      0   

         household_size_desc_2  household_size_desc_3  household_size_desc_4  \
user_id                                                                        
2499                         0                      1                      0   
2500                         0                      0                      0   

         household_size_desc_5+  kid_category_desc_1  kid_category_desc_2  \
user_id                                                                     
2499                          0                    1                    0   
2500                          0                    0                    0   

         kid_category_desc_3+  kid_category_desc_None/Unknown  
user_id                                                        
2499                        0                               0  
2500                        0                               0  

[2 rows x 41 columns]

In [17]:
user_features = csr_matrix(user_feat_lightfm.values).tocsr()
item_features = csr_matrix(item_feat_lightfm.values).tocsr()

In [30]:
%%time
model = LightFM(no_components=50,
                loss='warp',
                learning_rate=0.05, 
                item_alpha=0.1,
                user_alpha=0.1, 
                random_state=42
                )

model.fit((sparse_user_item > 0) * 1,
          sample_weight=coo_matrix(user_item_matrix),
          user_features=user_features,
          item_features=item_features,
          epochs=20, 
          num_threads=4
          ) 

In [31]:
user_emb = model.get_user_representations(features=user_features)

In [32]:
user_emb[0]

array([-80.30041 ,   0.      ,   0.      , ..., -83.69767 , -58.649616,
         0.      ], dtype=float32)

In [33]:
user_emb[0].shape

(2499,)

In [34]:
user_emb[1]

array([[ 6.4485972e-11, -3.7280173e-10,  4.5700491e-10, ...,
         1.7316035e-10, -1.3265244e-10,  8.9498975e-10],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       ...,
       [-2.2786950e-10, -1.4432844e-11,  1.8294596e-10, ...,
         1.8218735e-10,  1.7647073e-10,  7.3249884e-10],
       [-2.9505287e-12,  5.5499627e-10,  9.4617703e-11, ...,
        -4.1084713e-10,  5.1931748e-10,  9.5841535e-10],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00]], dtype=float32)

In [35]:
user_emb[1].shape

(2499, 50)

In [36]:
item_emb = model.get_item_representations(features=item_features)

In [37]:
item_emb[0].shape

(86865,)

In [38]:
item_emb[1].shape

(86865, 50)

In [39]:
%%time
train_precision = precision_at_k(model, sparse_user_item, 
                                 user_features=user_features,
                                 item_features=item_features,
                                 k=5).mean()

train_precision

CPU times: user 6min 31s, sys: 349 ms, total: 6min 31s
Wall time: 6min 35s


0.051700678

In [40]:
test_item_ids = np.array([1, 2, 3, 200, 1200])

predictions = model.predict(user_ids=0, item_ids=test_item_ids,
                            user_features=user_features,
                            item_features=item_features,
                            num_threads=4)

In [41]:
predictions

array([-80.61335 , -80.05226 , -80.045906, -80.389946, -80.03577 ],
      dtype=float32)